### ISSUE TITLE
Cant manually run audit via goss

### ISSUE THREAD

**Issue by Luiggi33** [ansible-lockdown/UBUNTU24-CIS-Audit#3]
**Describe the Issue**
When trying to execute the audit manually, it runs into an error and stops. Trying it via the sh file produces other, also flawed results.

**Expected Behavior**
It should run the audit accordingly.

**Actual Behavior**
After running the goss command from the README, I receive the error `Error: template: test:86:33: executing "test" at <.Vars.machine_uuid>: map has no entry for key "machine_uuid"`

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: N/A
- Host Python Version: N/A
- Ansible Server Python Version: N/A
- Additional Details:

**Comment by Luiggi33** [comment]
Hey @uk-bolly,
I can run it via the run_audit script, but trying to run it manually as described in the readme does not work.
Thanks in advance

**Comment by nman-hmcts** [comment]
Same issue.

```
root@linux02:/home/azureuser# goss --vars /home/azureuser/UBUNTU24-CIS-Audit/vars/CIS.yml -g /home/azureuser/UBUNTU24-CIS-Audit/goss.yml validate
Error: template: test:86:33: executing "test" at <.Vars.machine_uuid>: map has no entry for key "machine_uuid"
```

But running via script works. However I am not sure about the accuracy of the results. 

Why is the count showing 702 when there are only about 380 odd policies in total on the CIS recommendations.

```
root@linux02:/opt# ./UBUNTU24-CIS-Audit/run_audit.sh

## Pre-Checks Start

OK - Audit binary /usr/local/bin/goss is available
OK - Goss is installed and version is ok (0.4.9 >= 0.4.4)
OK - /opt/UBUNTU24-CIS-Audit/goss.yml is available

## Pre-checks Successful

#############
Audit Started
#############


    "summary": {
        "failed-count": 107,
        "skipped-count": 22,
        "summary-line": "Count: 702, Failed: 107, Skipped: 22, Duration: 14.013s",
        "test-count": 702,
Completed file can be found at /opt/audit_linux02-CIS-UBUNTU24_1729610744.json

```

**Comment by uk-bolly** [comment]
hi @Luiggi33 and @nman-hmcts 

You have highlighted something that does need clarification in the readme so i will get to that thank you.

**Running goss manually**

The goss component itself is normally run either manually or via the ansible remediation playbook utilising the script which contains extra variables used for meta data like the ```machine_uuid```. The are collected in the script and added as output.

In order to run it manually with the vars option you would need to edit the goss file and remove the entries from 79 and below so it does not expect those extra variables to be passed to it.

**Why different number of tests**

The audit itself may contains several tests per baseline control including the running state and the configured state. As well as confirming files exist etc, so this may mean some control may have 3 or 4 outputs.
Looking at the baselines you will see some controls have multiple components each of of those is treated separately to make it easier to fault find where something is not correct.

I hope that makes sense, i will be updating the README and readthedocs this morning

Kindest regards

uk-bolly

**Comment by uk-bolly** [comment]
Hi @Luiggi33 and @nman-hmcts 

I hope the previous statements make sense. I have now merged updated to readthedocs and updated the readme for this repo. 
Please let us know if we are missing anything or happy this now covers off the questions. 

Many thanks

Uk-bolly

**Comment by Luiggi33** [comment]
Hey @uk-bolly,

the updated version makes sense and resolves my question/issue.

Thanks a lot
